name: check-expo-dependencies
on:
  workflow_call:
    outputs:
      cancel-workflow:
        description: "Return 'true' if PR was closed and the workflow needs to be cancelled"
        value: ${{ jobs.check.outputs.cancel-workflow }}

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      cancel-workflow: ${{ steps.should-cancel-workflow.outputs.result }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - run: yarn

      - name: Check Expo version
        id: version
        run: node -p -e '`expo-package-version=${require("./package.json").dependencies.expo}`' >> $GITHUB_OUTPUT

      - name: Check if it is a bump that should be managed by Expo
        uses: actions/github-script@v6
        id: should-cancel-workflow
        with:
          result-encoding: string
          script: |
            const script = require(
              `${process.env.GITHUB_WORKSPACE}/scripts/check-expo-dependencies.js`
            );
            
            const shouldClosePR = await script({ 
              context, 
              github, 
              fetch,
              expoVersion: `${{ steps.version.outputs.expo-package-version }}`,
              prTitle: `${{ github.event.pull_request.title }}`
            });

            return shouldClosePR ? 'true' : 'false'


