name: check-expo-dependencies
on:
  workflow_call:
    outputs:
      cancel-workflow:
        description: "Return 'true' if PR was closed and the workflow needs to be cancelled"
        value: ${{ jobs.check.outputs.cancel-workflow }}

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      cancel-workflow: ${{ steps.should-cancel-workflow.outputs.result }}
    steps:
      - uses: actions/checkout@v3
      - name: Check if it is a dependency that should be managed by Expo
        uses: actions/github-script@v6
        id: should-cancel-workflow
        with:
          result-encoding: string
          script: |
            const script = require(
              `${process.env.GITHUB_WORKSPACE}/scripts/check-expo-dependencies.js`
            );

            const shouldClosePR = await script({ 
              context, 
              github, 
              fetch,
              prTitle: `${{ github.event.pull_request.title }}`
            });

            return String(shouldClosePR)


