name: expo-eas-clean

on:
  pull_request:
    types: [ closed ]

jobs:
  eas-clean:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v3
      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - run: eas channel:delete ${{ format('pr-{0}', github.event.number) }} --non-interactive
      - run: eas branch:delete ${{ format('pr-{0}', github.event.number) }} --json --non-interactive
